### ISSUE TITLE
P1673R12: Varna 2023 LWG review comments

### ISSUE THREAD

**Issue by mhoemmen** [ORNL/cpp-proposals-pub#391]
# Varna 2023 LWG review comments

## 2023/06/14

"your matrix_layout_policy isn’t a layout_policy because the latter needs to support any extent" -- not clear whether this is an action item.

### Change to mdspan's specification, not to P1673?

A possible problematic interpretation of [mdspan.layout.policy.reqmts].  Suggested edit: A type `MP` meets the layout mapping policy requirements if for a type `E` that is a specialization of `extents` such that `MP::mapping<E>` is valid, `MP::mapping<E>` denotes a type `X` that meets the layout mapping requirements ([mdspan.layout.reqmts]), and for which the qualified-id `X::layout_type` is valid and denotes the type `MP` and the qualified-id `X::extents_type` denotes `E`.

### TODO list

- [ ] Remove reference to P2642R2.  P1673 is orthogonal to P2642.
- [ ] Change the exposition-only _`is-mdspan`_ to be a variable template.
- [ ] Change "it will do so in read-only fashion" to "it does so ...."
- [ ] Implement changes in https://github.com/ORNL/cpp-proposals-pub/issues/390 (e.g., for _`in-vector`_ declaration form and "xT").
